### ISSUE TITLE
Support for /files/get-download-links

### ISSUE THREAD

**Issue by thiagofigueiro** [cenkalti/putio.py#47]
I noticed that the "Download links" action on the the web ui makes a POST request to https://api.put.io/v2/files/get-download-links, however this isn't documented in https://app.swaggerhub.com/apis-docs/putio/putio/2.6.3#/files and isn't currently available in this client.

When writing a client to synchronise data locally it would be useful to have this available so one doesn't need to traverse the directories and filter for VIDEO on all files.

**Comment by cenkalti** [comment]
The endpoint is undocumented because it is not part of the public API.

If you don't want to traverse, you can pass `-1` as `parent_id` param. This will return all files. There is a hard limit of 1000 on the number of entries returned from this endpoint. Please add `per_page=1000` parameter to get a `cursor` in response. Also you can filter file types by passing `file_type=VIDEO` param.

Example [httpie](https://httpie.org/) command:
```
http get 'https://api.put.io/v2/files/list' "Authorization: token $PUTIO_TOKEN" parent_id==-1 per_page==2 file_type==VIDEO
```
